### ISSUE TITLE
Tries to download and compile libzmq on ubuntu 16.04 x86_64 and give an error

### ISSUE THREAD

**Issue by aitorjs** [zeromq/zeromq.js#386]
**Describe the bug**

Been on a ubuntu 16.04 x86_64 machine, making **npm install zeromq@6.0.0-beta.6**, tries to download libzmq source and give an error. As the README.md table says, there is no need to download and compile libzmq source. ¿I'm right?

**Reproducing**

```
git pull ubuntu:16.04
docker run -it ubuntu:16.04 /bin/bash
# apt-get update
# apt-get install curl git make libzmq3-dev cmake python gcc g++ -y # use python 2.7, c++ 17
# curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
# export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
# nvm install 13.0
# npm init --y
# npm install zeromq@6.0.0-beta.6
```

**Expected behavior**

Tries to compile and give this error:
```
In file included from ../src/module.h:8:0,
                 from ../src/context.cc:3:
../src/util/arguments.h:6:20: fatal error: optional: No such file or directory
compilation terminated.
zeromq.target.mk:129: recipe for target 'Release/obj.target/zeromq/src/context.o' failed
make: *** [Release/obj.target/zeromq/src/context.o] Error 1
make: Leaving directory '/bitcoin/node_modules/zeromq/build'
```
This is the result of *uname -a*:
```
Linux f5b2b4e9218c 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Tested on**

 - OS: Ubunt 16.04
 - ZeroMQ.js version: 6.0.0-beta.6

Thanks! :)

**Comment by PeterJCLaw** [comment]
In case it's useful -- while I get this with `6.0.0-beta.6`, I don't get it for `6.0.0-beta.5`.

**Comment by rolftimmermans** [comment]
The prebuilt binaries are created with Ubuntu 18.04 bionic, so they might not work on 16.04? Installing from source should still work provided that you have all required dependencies as indicated [here](https://github.com/zeromq/zeromq.js#building-from-source).

**Comment by hirokiht** [comment]
I'm having the same problem in Ubuntu 16.04, the dependencies listed are installed however the pre-built binaries are not linked and compiling from source failed as well.

**Comment by ega-forever** [comment]
The same happens to me (on ubuntu 16.04) with version 6.0.0-beta.6. Downgrade to  6.0.0-beta.5 solved my issue
